# -*- coding: utf-8 -*-
"""Arnav Shukla BDA Final Project Code Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZH1Yiwo5lPOMYjlr3tNioVbZuiCQgaL
"""

# ============================================================
# MULTI-SOURCE SENTIMENT INTELLIGENCE SYSTEM WITH SHOCK DETECTION
# ============================================================
# Student: Arnav Shukla (E23CSEU0889)
# Subject: Big Data Analytics (CSET340)
# ============================================================
# TECH STACK:
#   Bronze  → Google Drive (raw CSV storage)
#   Silver  → Apache Spark (PySpark) — cleaning + TF-IDF
#   Gold    → Spark SQL (Hive-compatible) — analytical queries
#   Gold    → ML Models (LR, NB, SVM, RF) + LSTM Deep Learning
#   Viz     → Tableau Public



!pip install pyspark


from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col, lower, regexp_replace, when, length, trim, lit,
    count as spark_count, avg as spark_avg, sum as spark_sum
)
from pyspark.sql.types import IntegerType
from pyspark.ml.feature import Tokenizer, StopWordsRemover, CountVectorizer, IDF
from pyspark.ml import Pipeline
from pyspark.ml.classification import (
    LogisticRegression, NaiveBayes, LinearSVC, RandomForestClassifier
)
from pyspark.ml.evaluation import MulticlassClassificationEvaluator
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

# Spark session with Hive support enabled
spark = SparkSession.builder \
    .appName("MultiSource_Sentiment_Intelligence") \
    .config("spark.driver.memory", "4g") \
    .config("spark.sql.shuffle.partitions", "8") \
    .enableHiveSupport() \
    .getOrCreate()

print("=" * 65)
print("  MULTI-SOURCE SENTIMENT INTELLIGENCE SYSTEM")
print("  with Shock Detection using Big Data")
print("=" * 65)
print(f"  Spark Version : {spark.version}")
print(f"  Hive Support  : Enabled")
print(f"  Student       : Arnav Shukla (E23CSEU0889)")
print("=" * 65)

# =============================================================================
#   PHASE 1 — BRONZE LAYER (Raw Data Storage)
#   Bronze = Original, untouched CSV files stored in Google Drive
# =============================================================================


#Using Google Drive as Bronze storage:
from google.colab import drive
drive.mount('/content/drive')

AMAZON_PATH = '/content/drive/MyDrive/BDA_Project/Reviews.csv'
TWITTER_PATH = '/content/drive/MyDrive/BDA_Project/training.1600000.processed.noemoticon.csv'
NEWS_PATH = '/content/drive/MyDrive/BDA_Project/data.csv'

print("  Bronze Layer: Raw CSV file paths configured")
print(f"    Amazon:    {AMAZON_PATH}")
print(f"    Twitter:   {TWITTER_PATH}")
print(f"    Financial: {NEWS_PATH}")


print("\n" + "=" * 65)
print("  PHASE 1: BRONZE LAYER — Loading Raw Datasets")
print("=" * 65)

# Dataset 1: Amazon Fine Food Reviews
print("\n  [1/3] Amazon Fine Food Reviews...")
amazon_raw = spark.read.csv(AMAZON_PATH, header=True, inferSchema=True,
                            escape='"', multiLine=True)
print(f"        Records: {amazon_raw.count()}")
print(f"        Columns: {amazon_raw.columns}")

# Dataset 2: Twitter Sentiment140
print("\n  [2/3] Twitter Sentiment140...")
twitter_raw = spark.read.csv(TWITTER_PATH, header=False, inferSchema=False, escape='"')
twitter_raw = twitter_raw.toDF("target", "id", "date", "flag", "user", "text")
print(f"        Records: {twitter_raw.count()}")

# Dataset 3: Financial Phrase Bank
print("\n  [3/3] Financial Phrase Bank...")
news_raw = spark.read.csv(NEWS_PATH, header=True, inferSchema=True, escape='"')
print(f"        Records: {news_raw.count()}")

print("\n  BRONZE LAYER COMPLETE — 3 raw datasets loaded")

# =============================================================================
#   PHASE 2 — SILVER LAYER (Spark Cleaning + Feature Engineering)
#   Cleaning text, creating labels, building TF-IDF features
# =============================================================================



print("\n" + "=" * 65)
print("  PHASE 2: SILVER LAYER — Cleaning & Feature Engineering")
print("=" * 65)

# Amazon: Score >= 4 → Positive (1), Score <= 2 → Negative (0)
# Score 3 is neutral/ambiguous → we drop it for cleaner binary classification
print("\n  Cleaning Amazon Reviews...")
amazon_clean = amazon_raw \
    .select(col("Text").alias("text"), col("Score").cast(IntegerType()).alias("score")) \
    .filter(col("text").isNotNull() & col("score").isNotNull()) \
    .filter(col("score") != 3) \
    .withColumn("label", when(col("score") >= 4, 1).otherwise(0)) \
    .withColumn("source", lit("amazon")) \
    .withColumn("clean_text", lower(col("text"))) \
    .withColumn("clean_text", regexp_replace("clean_text", r"http\S+|www\S+", "")) \
    .withColumn("clean_text", regexp_replace("clean_text", r"<.*?>", "")) \
    .withColumn("clean_text", regexp_replace("clean_text", r"[^a-zA-Z\s]", "")) \
    .withColumn("clean_text", regexp_replace("clean_text", r"\s+", " ")) \
    .withColumn("clean_text", trim(col("clean_text"))) \
    .filter(length(col("clean_text")) > 10) \
    .select("clean_text", "label", "source")

print(f"  Amazon cleaned: {amazon_clean.count()} records")
amazon_clean.groupBy("label").count().show()


# Twitter: target 0 = negative, target 4 = positive → convert to 0/1
# We sample 100K per class to keep Colab manageable
print("  Cleaning Twitter Data...")
twitter_clean = twitter_raw \
    .select(col("text"), col("target").cast(IntegerType())) \
    .filter(col("text").isNotNull()) \
    .withColumn("label", when(col("target") == 4, 1).otherwise(0)) \
    .withColumn("source", lit("twitter")) \
    .withColumn("clean_text", lower(col("text"))) \
    .withColumn("clean_text", regexp_replace("clean_text", r"@\w+", "")) \
    .withColumn("clean_text", regexp_replace("clean_text", r"http\S+|www\S+", "")) \
    .withColumn("clean_text", regexp_replace("clean_text", r"#\w+", "")) \
    .withColumn("clean_text", regexp_replace("clean_text", r"[^a-zA-Z\s]", "")) \
    .withColumn("clean_text", regexp_replace("clean_text", r"\s+", " ")) \
    .withColumn("clean_text", trim(col("clean_text"))) \
    .filter(length(col("clean_text")) > 10) \
    .select("clean_text", "label", "source")

# Balanced sampling: 100K positive + 100K negative
twitter_clean = twitter_clean.filter(col("label") == 1).limit(100000) \
    .union(twitter_clean.filter(col("label") == 0).limit(100000))

print(f"  Twitter cleaned: {twitter_clean.count()} records")
twitter_clean.groupBy("label").count().show()


# Financial: "positive" → 1, "negative" → 0, "neutral" → drop
print("  Cleaning Financial News Data...")
news_clean = news_raw \
    .select(col("Sentence").alias("text"), col("Sentiment").alias("sentiment_str")) \
    .filter(col("text").isNotNull()) \
    .filter(col("sentiment_str").isin("positive", "negative")) \
    .withColumn("label", when(col("sentiment_str") == "positive", 1).otherwise(0)) \
    .withColumn("source", lit("financial")) \
    .withColumn("clean_text", lower(col("text"))) \
    .withColumn("clean_text", regexp_replace("clean_text", r"[^a-zA-Z\s]", "")) \
    .withColumn("clean_text", regexp_replace("clean_text", r"\s+", " ")) \
    .withColumn("clean_text", trim(col("clean_text"))) \
    .filter(length(col("clean_text")) > 10) \
    .select("clean_text", "label", "source")

print(f"  Financial cleaned: {news_clean.count()} records")
news_clean.groupBy("label").count().show()

print("=" * 65)
print("  COMBINING ALL 3 DATASETS")
print("=" * 65)

combined_df = amazon_clean.union(twitter_clean).union(news_clean)
print(f"  Total combined: {combined_df.count()} records")
combined_df.groupBy("source").count().orderBy("source").show()
combined_df.groupBy("label").count().show()


# Pipeline: Raw Text → Tokenize → Remove Stopwords → CountVectorize → TF-IDF
# This converts text into numerical feature vectors for ML models

print("=" * 65)
print("  BUILDING NLP PIPELINE: Tokenize → Stopwords → TF-IDF")
print("=" * 65)

tokenizer = Tokenizer(inputCol="clean_text", outputCol="words")
remover = StopWordsRemover(inputCol="words", outputCol="filtered_words")
cv = CountVectorizer(inputCol="filtered_words", outputCol="raw_features",
                     vocabSize=10000, minDF=5)
idf = IDF(inputCol="raw_features", outputCol="features")

nlp_pipeline = Pipeline(stages=[tokenizer, remover, cv, idf])

print("  Fitting pipeline on combined data...")
nlp_model = nlp_pipeline.fit(combined_df)
featured_df = nlp_model.transform(combined_df)

feat_size = featured_df.select("features").first()[0].size
print(f"  Feature vector dimension: {feat_size}")
print("\n  SILVER LAYER COMPLETE!")
featured_df.select("clean_text", "label", "source").show(5, truncate=50)

# =============================================================================
#   PHASE 3 — GOLD LAYER PART A: ML MODEL TRAINING
#   4 Spark ML Models: LR, NB, SVM, RF (each from a different ML family)
#     LR  = Linear model (draws a straight decision boundary)
#     NB  = Probabilistic model (uses word frequency statistics)
#     SVM = Margin-based model (maximizes gap between classes)
#     RF  = Ensemble model (combines 20 decision trees)
# =============================================================================


print("\n" + "=" * 65)
print("  PHASE 3: GOLD LAYER — ML Model Training")
print("=" * 65)

train, test = featured_df.randomSplit([0.8, 0.2], seed=42)
print(f"  Training: {train.count()} | Test: {test.count()}")
train.groupBy("label").count().show()


print("  TRAINING 4 SPARK ML MODELS...")

# Model 1: Logistic Regression
print("\n  [1/4] Logistic Regression (Linear Model)...")
lr = LogisticRegression(featuresCol="features", labelCol="label", maxIter=10)
lr_model = lr.fit(train)
lr_pred = lr_model.transform(test)
print("        Done!")

# Model 2: Naive Bayes
print("  [2/4] Naive Bayes (Probabilistic Model)...")
nb = NaiveBayes(featuresCol="features", labelCol="label", modelType="multinomial")
nb_model = nb.fit(train)
nb_pred = nb_model.transform(test)
print("        Done!")

# Model 3: SVM (LinearSVC)
print("  [3/4] SVM — LinearSVC (Margin-Based Model)...")
svm = LinearSVC(featuresCol="features", labelCol="label", maxIter=10)
svm_model = svm.fit(train)
svm_pred = svm_model.transform(test)
print("        Done!")

# Model 4: Random Forest
print("  [4/4] Random Forest (Ensemble Model)...")
rf = RandomForestClassifier(featuresCol="features", labelCol="label", numTrees=20)
rf_model = rf.fit(train)
rf_pred = rf_model.transform(test)
print("        Done!")

print("\n  All 4 Spark ML models trained!")


print("\n" + "=" * 65)
print("  MODEL EVALUATION")
print("=" * 65)

eval_acc = MulticlassClassificationEvaluator(labelCol="label", metricName="accuracy")
eval_f1 = MulticlassClassificationEvaluator(labelCol="label", metricName="f1")
eval_prec = MulticlassClassificationEvaluator(labelCol="label", metricName="weightedPrecision")
eval_rec = MulticlassClassificationEvaluator(labelCol="label", metricName="weightedRecall")

models_dict = {
    "Logistic Regression": lr_pred,
    "Naive Bayes": nb_pred,
    "SVM (LinearSVC)": svm_pred,
    "Random Forest": rf_pred
}

results = []
for name, pred in models_dict.items():
    acc = eval_acc.evaluate(pred)
    prec = eval_prec.evaluate(pred)
    rec = eval_rec.evaluate(pred)
    f1 = eval_f1.evaluate(pred)
    results.append({
        "Model": name, "Accuracy": round(acc, 4),
        "Precision": round(prec, 4), "Recall": round(rec, 4),
        "F1-Score": round(f1, 4)
    })
    print(f"  {name}:  Acc={acc:.4f} | F1={f1:.4f} | Prec={prec:.4f} | Rec={rec:.4f}")

results_df = pd.DataFrame(results)
print("\n" + results_df.to_string(index=False))


print("\n" + "=" * 65)
print("  PER-SOURCE MODEL PERFORMANCE")
print("=" * 65)

model_objs = [("LR", lr_model), ("NB", nb_model), ("SVM", svm_model), ("RF", rf_model)]
source_results = []

for src in ["amazon", "twitter", "financial"]:
    src_test = test.filter(col("source") == src)
    if src_test.count() == 0:
        continue
    print(f"\n  --- {src.upper()} ({src_test.count()} test records) ---")
    for mname, mobj in model_objs:
        sp = mobj.transform(src_test)
        acc = eval_acc.evaluate(sp)
        f1 = eval_f1.evaluate(sp)
        source_results.append({
            "Source": src, "Model": mname,
            "Accuracy": round(acc, 4), "F1-Score": round(f1, 4)
        })
        print(f"    {mname}: Acc={acc:.4f} | F1={f1:.4f}")

source_results_df = pd.DataFrame(source_results)

test_pd = test.select("clean_text", "label", "source").toPandas()
test_pd["lr_pred"] = lr_pred.select("prediction").toPandas()["prediction"].astype(int)
test_pd["nb_pred"] = nb_pred.select("prediction").toPandas()["prediction"].astype(int)
test_pd["svm_pred"] = svm_pred.select("prediction").toPandas()["prediction"].astype(int)
test_pd["rf_pred"] = rf_pred.select("prediction").toPandas()["prediction"].astype(int)

# Ensemble: majority vote (3 out of 4 agree)
test_pd["ensemble_pred"] = (
    test_pd[["lr_pred", "nb_pred", "svm_pred", "rf_pred"]].sum(axis=1) >= 3
).astype(int)

test_pd.insert(0, "row_id", range(len(test_pd)))
ens_acc = (test_pd["ensemble_pred"] == test_pd["label"]).mean()
print(f"\n  Ensemble (Majority Vote) Accuracy: {ens_acc:.4f}")


colors = ['#1f77b4', '#ff7f0e', '#d62728', '#2ca02c']

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
ax1 = axes[0]
bars = ax1.barh(results_df["Model"], results_df["Accuracy"], color=colors, edgecolor='white')
ax1.set_xlabel("Accuracy"); ax1.set_title("Model Accuracy", fontsize=14, fontweight='bold')
ax1.set_xlim(0, 1)
for bar, val in zip(bars, results_df["Accuracy"]):
    ax1.text(val + 0.01, bar.get_y() + bar.get_height()/2, f'{val:.4f}', va='center')

ax2 = axes[1]
bars = ax2.barh(results_df["Model"], results_df["F1-Score"], color=colors, edgecolor='white')
ax2.set_xlabel("F1-Score"); ax2.set_title("Model F1-Score", fontsize=14, fontweight='bold')
ax2.set_xlim(0, 1)
for bar, val in zip(bars, results_df["F1-Score"]):
    ax2.text(val + 0.01, bar.get_y() + bar.get_height()/2, f'{val:.4f}', va='center')

plt.tight_layout()
plt.savefig("chart_model_comparison.png", dpi=150, bbox_inches='tight')
plt.show()
print("  Saved chart_model_comparison.png")


from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

fig, axes = plt.subplots(1, 5, figsize=(25, 5))
for idx, (name, col_name) in enumerate([
    ("Logistic Regression", "lr_pred"), ("Naive Bayes", "nb_pred"),
    ("SVM", "svm_pred"), ("Random Forest", "rf_pred"),
    ("Ensemble", "ensemble_pred")
]):
    cm = confusion_matrix(test_pd["label"], test_pd[col_name])
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Neg", "Pos"])
    disp.plot(ax=axes[idx], cmap='Blues', values_format='d')
    axes[idx].set_title(name, fontsize=11, fontweight='bold')

plt.suptitle("Confusion Matrices", fontsize=14, fontweight='bold', y=1.05)
plt.tight_layout()
plt.savefig("chart_confusion_matrices.png", dpi=150, bbox_inches='tight')
plt.show()
print("  Saved chart_confusion_matrices.png")

# =============================================================================
#   PHASE 3b — GOLD LAYER PART B: LSTM DEEP LEARNING
#   LSTM reads text as a SEQUENCE — captures word order & context
#   This is fundamentally different from the bag-of-words Spark models
# =============================================================================


import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Embedding, LSTM, Dense, Dropout,
    Bidirectional, SpatialDropout1D
)
from tensorflow.keras.preprocessing.text import Tokenizer as KerasTokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report

print("\n" + "=" * 65)
print("  PHASE 3b: LSTM DEEP LEARNING MODEL")
print(f"  TensorFlow: {tf.__version__}")
print(f"  GPU: {tf.config.list_physical_devices('GPU')}")
print("=" * 65)

# Preparing data for LSTM (needs integer sequences, not TF-IDF)
df_pd = combined_df.select("clean_text", "label", "source").toPandas()

MAX_WORDS = 20000
MAX_LEN = 50
EMBEDDING_DIM = 32

keras_tok = KerasTokenizer(num_words=MAX_WORDS, oov_token="<OOV>")
keras_tok.fit_on_texts(df_pd["clean_text"].values)
sequences = keras_tok.texts_to_sequences(df_pd["clean_text"].values)
X = pad_sequences(sequences, maxlen=MAX_LEN, padding='post', truncating='post')
y = df_pd["label"].values
src_arr = df_pd["source"].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)
_, src_test = train_test_split(
    src_arr, test_size=0.2, random_state=42, stratify=y)

print(f"  Vocab: {min(len(keras_tok.word_index), MAX_WORDS)} | Seq shape: {X.shape}")
print(f"  Train: {X_train.shape[0]} | Test: {X_test.shape[0]}")


# Bidirectional LSTM: reads text left-to-right AND right-to-left
# This helps it understand context from both directions
model = Sequential([
    Embedding(MAX_WORDS, EMBEDDING_DIM, input_length=MAX_LEN),
    Bidirectional(LSTM(32, dropout=0.2)),
    Dense(32, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

history = model.fit(
    X_train, y_train, epochs=3, batch_size=1024,
    validation_split=0.15,
    callbacks=[
        EarlyStopping(monitor='val_loss', patience=3,
                      restore_best_weights=True, verbose=1),
        ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                          patience=2, min_lr=1e-6, verbose=1)
    ],
    verbose=1
)



fig, axes = plt.subplots(1, 2, figsize=(14, 5))
axes[0].plot(history.history['accuracy'], label='Train', lw=2)
axes[0].plot(history.history['val_accuracy'], label='Val', lw=2)
axes[0].set_title('LSTM Accuracy', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Accuracy')
axes[0].legend(); axes[0].grid(True, alpha=0.3)

axes[1].plot(history.history['loss'], label='Train', lw=2, color='#d62728')
axes[1].plot(history.history['val_loss'], label='Val', lw=2, color='#ff7f0e')
axes[1].set_title('LSTM Loss', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Loss')
axes[1].legend(); axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("chart_lstm_training.png", dpi=150, bbox_inches='tight')
plt.show()

y_prob = model.predict(X_test, batch_size=256, verbose=0)
y_pred_lstm = (y_prob > 0.5).astype(int).flatten()

lstm_acc = accuracy_score(y_test, y_pred_lstm)
lstm_prec = precision_score(y_test, y_pred_lstm)
lstm_rec = recall_score(y_test, y_pred_lstm)
lstm_f1 = f1_score(y_test, y_pred_lstm)

print("=" * 65)
print("  LSTM RESULTS")
print("=" * 65)
print(f"  Acc={lstm_acc:.4f} | Prec={lstm_prec:.4f} | Rec={lstm_rec:.4f} | F1={lstm_f1:.4f}")
print(classification_report(y_test, y_pred_lstm, target_names=['Negative', 'Positive']))

# Per-source
lstm_src = []
for src in ["amazon", "twitter", "financial"]:
    m = src_test == src
    if sum(m) == 0: continue
    sa = accuracy_score(y_test[m], y_pred_lstm[m])
    sf = f1_score(y_test[m], y_pred_lstm[m])
    lstm_src.append({"Source": src, "Accuracy": round(sa, 4), "F1": round(sf, 4)})
    print(f"  {src.upper()}: Acc={sa:.4f} | F1={sf:.4f}")

# Confusion matrix
fig, ax = plt.subplots(figsize=(7, 5))
cm = confusion_matrix(y_test, y_pred_lstm)
ConfusionMatrixDisplay(cm, display_labels=["Neg", "Pos"]).plot(ax=ax, cmap='Purples')
ax.set_title("LSTM Confusion Matrix", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig("chart_lstm_confusion.png", dpi=150, bbox_inches='tight')
plt.show()



print("\n" + "=" * 65)
print("  FINAL COMPARISON — ALL 5 MODELS")
print("=" * 65)

all_results = results.copy()
all_results.append({
    "Model": "LSTM (BiLSTM)", "Accuracy": round(lstm_acc, 4),
    "Precision": round(lstm_prec, 4), "Recall": round(lstm_rec, 4),
    "F1-Score": round(lstm_f1, 4)
})
all_df = pd.DataFrame(all_results)
print(all_df.to_string(index=False))

best = all_df.loc[all_df["Accuracy"].idxmax()]
print(f"\n  BEST MODEL: {best['Model']} (Accuracy: {best['Accuracy']})")

# Final chart
fig, ax = plt.subplots(figsize=(12, 6))
x = range(len(all_df))
w = 0.35
b1 = ax.bar([i-w/2 for i in x], all_df["Accuracy"], w, label='Accuracy', color='#2196F3')
b2 = ax.bar([i+w/2 for i in x], all_df["F1-Score"], w, label='F1-Score', color='#FF9800')
ax.set_xticks(list(x))
ax.set_xticklabels(all_df["Model"], rotation=15, ha='right')
ax.set_ylim(0, 1.15); ax.set_ylabel("Score")
ax.set_title("All 5 Models — Accuracy vs F1-Score", fontsize=14, fontweight='bold')
ax.legend(); ax.grid(axis='y', alpha=0.3)
for bar in b1:
    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.01,
            f'{bar.get_height():.3f}', ha='center', fontsize=10)
for bar in b2:
    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.01,
            f'{bar.get_height():.3f}', ha='center', fontsize=10)
plt.tight_layout()
plt.savefig("chart_all_models.png", dpi=150, bbox_inches='tight')
plt.show()

# =============================================================================
#   PHASE 4 — SENTIMENT SHOCK DETECTION
#   Detects sudden sentiment shifts using Rolling Z-Score
# =============================================================================



print("\n" + "=" * 65)
print("  PHASE 4: SENTIMENT SHOCK DETECTION")
print("  Method: Rolling Window Z-Score Anomaly Detection")
print("=" * 65)

WINDOW_SIZE = 50
ROLLING_WINDOW = 5
Z_THRESHOLD = 1.4

all_shocks = []

for src in ["amazon", "twitter", "financial"]:
    sd = test_pd[test_pd["source"] == src].copy().reset_index(drop=True)
    if len(sd) < WINDOW_SIZE * 3:
        print(f"  {src.upper()}: Not enough data, skipping")
        continue

    sd["time_index"] = sd.index // WINDOW_SIZE
    ts = sd.groupby("time_index").agg(
        sentiment_avg=("ensemble_pred", "mean"),
        n=("ensemble_pred", "count")
    ).reset_index()
    ts = ts[ts["n"] >= WINDOW_SIZE // 2]

    ts["rolling_mean"] = ts["sentiment_avg"].rolling(ROLLING_WINDOW, min_periods=2).mean()
    ts["rolling_std"] = ts["sentiment_avg"].rolling(ROLLING_WINDOW, min_periods=2).std()
    ts["z_score"] = ((ts["sentiment_avg"] - ts["rolling_mean"]) /
                     ts["rolling_std"].replace(0, np.nan)).fillna(0)
    ts["is_shock"] = abs(ts["z_score"]) > Z_THRESHOLD
    ts["source"] = src

    sc = ts["is_shock"].sum()
    print(f"  {src.upper()}: {len(ts)} time points | {sc} shocks ({sc/len(ts)*100:.1f}%)")
    all_shocks.append(ts)

shock_df = pd.concat(all_shocks, ignore_index=True)


srcs = shock_df["source"].unique()
clrs = {"amazon": "#FF9900", "twitter": "#1DA1F2", "financial": "#00C853"}

fig, axes = plt.subplots(len(srcs), 1, figsize=(16, 5 * len(srcs)))
if len(srcs) == 1: axes = [axes]

for i, src in enumerate(srcs):
    ax = axes[i]
    ts = shock_df[shock_df["source"] == src]
    ax.plot(ts["time_index"], ts["sentiment_avg"], color=clrs.get(src, "#333"),
            lw=1.5, alpha=0.8, label="Sentiment")
    ax.plot(ts["time_index"], ts["rolling_mean"], color='#666', lw=2,
            ls='--', alpha=0.7, label="Rolling Mean")
    up = ts["rolling_mean"] + Z_THRESHOLD * ts["rolling_std"]
    lo = ts["rolling_mean"] - Z_THRESHOLD * ts["rolling_std"]
    ax.fill_between(ts["time_index"], lo, up, alpha=0.15, color='gray', label="±2σ Band")

    shk = ts[ts["is_shock"]]
    if len(shk) > 0:
        ax.scatter(shk["time_index"], shk["sentiment_avg"], color='red', s=100,
                   zorder=5, edgecolors='darkred', lw=1.5, label=f"Shocks ({len(shk)})")
        for _, s in shk.iterrows():
            ax.axvline(s["time_index"], color='red', alpha=0.15, lw=1)

    ax.set_title(f"Shock Detection — {src.upper()}", fontsize=14, fontweight='bold')
    ax.set_xlabel("Time Index"); ax.set_ylabel("Avg Sentiment")
    ax.set_ylim(-0.1, 1.1); ax.legend(loc='upper right'); ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("chart_sentiment_shocks.png", dpi=150, bbox_inches='tight')
plt.show()

# Dashboard
fig, axes = plt.subplots(2, 2, figsize=(16, 10))
ax1 = axes[0, 0]
for src in srcs:
    ts = shock_df[shock_df["source"] == src]
    t = np.linspace(0, 1, len(ts))
    ax1.plot(t, ts["sentiment_avg"].values, color=clrs.get(src, "#333"),
             lw=1.5, label=src.upper(), alpha=0.8)
ax1.set_title("All Sources Overlay", fontsize=12, fontweight='bold')
ax1.legend(); ax1.grid(True, alpha=0.3)

ax2 = axes[0, 1]
sc = shock_df.groupby("source")["is_shock"].sum()
ax2.bar(sc.index, sc.values, color=[clrs.get(s, "#333") for s in sc.index])
ax2.set_title("Shocks per Source", fontsize=12, fontweight='bold')
ax2.grid(axis='y', alpha=0.3)

ax3 = axes[1, 0]
av = shock_df.groupby("source")["sentiment_avg"].mean()
ax3.bar(av.index, av.values, color=[clrs.get(s, "#333") for s in av.index])
ax3.set_title("Avg Sentiment", fontsize=12, fontweight='bold')
ax3.set_ylim(0, 1); ax3.grid(axis='y', alpha=0.3)

ax4 = axes[1, 1]
vo = shock_df.groupby("source")["sentiment_avg"].std()
ax4.bar(vo.index, vo.values, color=[clrs.get(s, "#333") for s in vo.index])
ax4.set_title("Volatility (Std Dev)", fontsize=12, fontweight='bold')
ax4.grid(axis='y', alpha=0.3)

plt.suptitle("Sentiment Intelligence Dashboard", fontsize=15, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig("chart_dashboard.png", dpi=150, bbox_inches='tight')
plt.show()

# =============================================================================
#   PHASE 5 — SPARK SQL (Hive-Compatible Analytical Queries)
#   This replaces the need for a separate Hive installation
#   Spark SQL uses HiveQL syntax and Hive metastore
# =============================================================================



print("\n" + "=" * 65)
print("  PHASE 5: SPARK SQL — Hive-Compatible Analytical Queries")
print("=" * 65)

# Converting Pandas DataFrames to Spark DataFrames and register as SQL tables
# This is equivalent to creating Hive tables

# Table 1: Model Metrics
metrics_rows = []
for r in all_results:
    metrics_rows.append((r["Model"], r["Accuracy"], r["Precision"],
                         r["Recall"], r["F1-Score"], "overall"))
for _, row in source_results_df.iterrows():
    metrics_rows.append((row["Model"], row["Accuracy"], 0.0,
                         0.0, row["F1-Score"], row["Source"]))
for r in lstm_src:
    metrics_rows.append(("LSTM", r["Accuracy"], 0.0, 0.0, r["F1"], r["Source"]))

metrics_spark = spark.createDataFrame(
    metrics_rows,
    ["model_name", "accuracy", "precision_val", "recall_val", "f1_score", "source"]
)
metrics_spark.createOrReplaceTempView("model_metrics")

# Table 2: Predictions
pred_spark = spark.createDataFrame(
    test_pd[["row_id", "source", "label", "ensemble_pred"]].rename(
        columns={"label": "actual_label", "ensemble_pred": "predicted_label"}
    )
)
pred_spark.createOrReplaceTempView("sentiment_predictions")

# Table 3: Shock Detection
shock_spark = spark.createDataFrame(
    shock_df[["time_index", "sentiment_avg", "rolling_mean",
              "rolling_std", "z_score", "is_shock", "source"]]
)
shock_spark.createOrReplaceTempView("shock_detection")

print("  3 SQL tables registered:")
print("    • model_metrics")
print("    • sentiment_predictions")
print("    • shock_detection")



print("\n" + "=" * 65)
print("  RUNNING HIVE-COMPATIBLE SQL QUERIES")
print("=" * 65)

# Query 1: Overall model ranking by accuracy
print("\n  --- Query 1: Model Ranking (Overall) ---")
spark.sql("""
    SELECT model_name, accuracy, f1_score
    FROM model_metrics
    WHERE source = 'overall'
    ORDER BY accuracy DESC
""").show()

# Query 2: Best model per source
print("  --- Query 2: Best Model per Source ---")
spark.sql("""
    SELECT source, model_name, accuracy
    FROM model_metrics m1
    WHERE source != 'overall'
    AND accuracy = (
        SELECT MAX(accuracy) FROM model_metrics m2
        WHERE m2.source = m1.source AND m2.source != 'overall'
    )
""").show()

# Query 3: Sentiment distribution per source
print("  --- Query 3: Sentiment Distribution ---")
spark.sql("""
    SELECT source,
           predicted_label AS sentiment,
           COUNT(*) AS count
    FROM sentiment_predictions
    GROUP BY source, predicted_label
    ORDER BY source, sentiment
""").show()

# Query 4: Positive vs Negative percentage
print("  --- Query 4: Positive vs Negative % ---")
spark.sql("""
    SELECT source,
           ROUND(SUM(CASE WHEN predicted_label = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS positive_pct,
           ROUND(SUM(CASE WHEN predicted_label = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS negative_pct
    FROM sentiment_predictions
    GROUP BY source
""").show()

# Query 5: Prediction accuracy per source
print("  --- Query 5: Accuracy per Source ---")
spark.sql("""
    SELECT source,
           COUNT(*) AS total,
           SUM(CASE WHEN actual_label = predicted_label THEN 1 ELSE 0 END) AS correct,
           ROUND(SUM(CASE WHEN actual_label = predicted_label THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS accuracy_pct
    FROM sentiment_predictions
    GROUP BY source
""").show()

# Query 6: Shock summary
print("  --- Query 6: Shock Detection Summary ---")
spark.sql("""
    SELECT source,
           COUNT(*) AS total_points,
           SUM(CASE WHEN is_shock = true THEN 1 ELSE 0 END) AS shocks,
           ROUND(AVG(sentiment_avg), 4) AS avg_sentiment,
           ROUND(MAX(z_score), 3) AS max_zscore
    FROM shock_detection
    GROUP BY source
""").show()

print("  All 6 SQL queries executed successfully!")



print("\n" + "=" * 65)
print("  EXPORTING CSVs FOR TABLEAU")
print("=" * 65)

# Exporting all data needed for Tableau dashboards
metrics_export = pd.DataFrame(metrics_rows,
    columns=["model_name", "accuracy", "precision_val", "recall_val", "f1_score", "source"])
metrics_export.to_csv("model_metrics.csv", index=False)
print(f"  1. model_metrics.csv         ({len(metrics_export)} rows)")

pred_export = test_pd[["row_id", "source", "label", "ensemble_pred"]].copy()
pred_export.columns = ["row_id", "source", "actual_label", "predicted_label"]
pred_export.to_csv("sentiment_predictions.csv", index=False)
print(f"  2. sentiment_predictions.csv ({len(pred_export)} rows)")

shock_df.to_csv("shock_detection.csv", index=False)
print(f"  3. shock_detection.csv       ({len(shock_df)} rows)")

test_pd.to_csv("full_predictions.csv", index=False)
print(f"  4. full_predictions.csv      ({len(test_pd)} rows)")

print("\n" + "=" * 65)
print("  PROJECT EXECUTION COMPLETE!")
print("=" * 65)
print("""
  SUMMARY OF OUTPUTS:
  ─────────────────────────────────────────
  CSVs (for Tableau):
    • model_metrics.csv
    • sentiment_predictions.csv
    • shock_detection.csv
    • full_predictions.csv

  Charts (for Report):
    • chart_model_comparison.png
    • chart_confusion_matrices.png
    • chart_lstm_training.png
    • chart_lstm_confusion.png
    • chart_all_models.png
    • chart_sentiment_shocks.png
    • chart_dashboard.png
  ─────────────────────────────────────────

""")